sudo: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/wrapper
language: java
jdk:
  - oraclejdk7
script:
  - ./gradlew pullRequestValidation
env:
  - TERM=dumb
branches:
  only:
    - master
