name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: TG908/fork-sync@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: llvm
